Lab3/Lab3/Models/DrugModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3.Models
{
    public class DrugModel
    {

        public int Uid { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Producer { get; set; }

        public double Price { get; set; }

        public int Stock { get; set; }

        public int CompareTo(DrugModel other)
        {
            if (this.Name.CompareTo(other.Name) > 0)
                return -1;
            else if (this.Name.CompareTo(other.Name) < 0)
                return 1;
            else
                return 0;
        }

    }
}

Lab3/Lab3/Controllers/PharmacyController.cs
using Lab3.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DStructures;
using System.Linq;

namespace Lab3.Controllers
{
    public class PharmacyController : Controller
    {
        private static Tree<string, DrugModel> MyTree;

        [HttpGet]
        public ActionResult LoadTree()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoadTree(HttpPostedFileBase csvFile)
        {

            MyTree = new Tree<string, DrugModel>();
            ReadFile(csvFile);

            return View();

        }


        [HttpGet]
        public ActionResult Orders()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Refill()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Search()
        {
            return View();
        }


        [HttpGet]
        public ActionResult TraverseTree()
        {
            return View();
        }

        private bool ReadFile(HttpPostedFileBase csvFile)
        {
            bool succeed = false;

            string path = string.Empty;

            if (csvFile != null)
            {
                if (".csv".Equals(Path.GetExtension(csvFile.FileName), StringComparison.OrdinalIgnoreCase))
                {
                    string fileName = Path.GetFileName(csvFile.FileName);
                    path = Path.Combine(Server.MapPath("~/App_Data/Files"), fileName);
                    csvFile.SaveAs(path);

                    string file = System.IO.File.ReadAllText(path);
                    foreach (string line in file.Split('\n'))
                    {
                        if (!string.IsNullOrEmpty(line))
                        {
                            string[] items = Regex.Split(line, ",(?=(?:[^\"]*\"[^\"]*\")*(?![^\"]*\"))");

                            try
                            {
                                DrugModel Drug = new DrugModel()
                                {
                                    Uid = int.Parse(items[0]),
                                    Name = items[1],
                                    Description = items[2],
                                    Producer = items[3],
                                    Price = float.Parse(items[4].Trim('$')),
                                    Stock = int.Parse(items[5])
                                };
                                MyTree.Insert(Drug.Name, Drug);
                                succeed = true;
                            }
                            catch (Exception)
                            {
                                MyTree.WipeOut();
                                return false;
                            }
                        }
                    }
                }
            }
            return succeed;
        }
    }
}

Lab3/Lab3/Views/Partial/Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/scripts")
</head>
<body>
    <header>
        <div class="container">
            <div class="twelve columns">
                <nav class="u-pull-right">
                    <ul>
                        <li class="menuopts">@Html.ActionLink("Cargar árbol", "LoadTree", "Pharmacy")</li>
                        <li>@Html.ActionLink("Pedidos", "Orders", "Pharmacy")</li>
                        <li>@Html.ActionLink("Reabastecimiento", "Refill", "Pharmacy")</li>
                        <li>@Html.ActionLink("Búsqueda de fármacos", "Search", "Pharmacy")</li>
                        <li>@Html.ActionLink("Recorrer árbol", "TraverseTree", "Pharmacy")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()
    @RenderSection("scripts", required: false)
</body>
</html>

Lab3/Lab3/Views/Pharmacy/LoadTree.cshtml
@{
    ViewBag.Title = "LoadTree";
    Layout = "~/Views/Partial/Layout.cshtml";
}

<center><h5 style="padding: 10px">Cargar fármacos al árbol binario :)</h5></center>
<div>
    <form class="form" id="btreeform" action=@Url.Action("LoadTree") method="post" enctype="multipart/form-data">
        <input type="file" class="textbox" name="csvFile" id="csvFile" accept=".csv" required />
        <input type="submit" class="button-primary btn" name="Enter" value="Cargar" />
    </form>
</div>

Lab3/Lab3/Views/Pharmacy/Orders.cshtml
@{
    ViewBag.Title = "Orders";
    Layout = "~/Views/Partial/Layout.cshtml";
}

<center><h5 style="padding: 10px">Hacer pedidos</h5></center>
<div>
    <form class="form" id="ordersform" action=@Url.Action("Orders") method="post">
        <input type="text" class="textbox" name="name" placeholder="Nombre" required />
        <input type="text" class="textbox" name="address" placeholder="Dirección" required />
        <input type="number" class="textbox" name="nit" min="0" max="2147483647" placeholder="NIT" required />
        <input type="number" class="textbox" name="meds" min="0" max="2147483647" placeholder="Fármacos" required />
        <input type="submit" class="button-primary btn" name="Enter" value="Ordenar" />
    </form>
</div>

Lab3/Lab3/Views/Pharmacy/Refill.cshtml
@{
    ViewBag.Title = "Refill";
    Layout = "~/Views/Partial/Layout.cshtml";
}

<center><h5 style="padding: 10px">Reabastecer medicamentos</h5></center>
<div>
    <form class="form" id="btreeform" action=@Url.Action("Refill") method="post">
        <input type="number" class="textbox" name="order" min="0" max="2147483647" placeholder="Fármacos" required />
        <input type="submit" class="button-primary btn" name="Enter" value="Reabastecer" />
    </form>
</div>

Lab3/Lab3/Views/Pharmacy/Search.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Partial/Layout.cshtml";
}

<h2>Search</h2>

Lab3/Lab3/Views/Pharmacy/TraverseTree.cshtml
@{
    ViewBag.Title = "TraverseTree";
    Layout = "~/Views/Partial/Layout.cshtml";
}

<h2>TraverseTree</h2>